SELECT * FROM MARKET_PLACE.MARKET_USERS
SELECT * FROM MARKET_PLACE.MARKET_ITEMS
SELECT * FROM MARKET_PLACE.MARKET_ORDERS

SELECT * FROM MARKET_PLACE.ITEM_IMAGES
SELECT * FROM MARKET_PLACE.HISTORY
SELECT * FROM MARKET_PLACE.MARKET_PERSONS

SELECT * FROM MARKET_PLACE.ITEMS_FAVORITE

/*
UPDATE MARKET_PLACE.MARKET_USERS
	SET BALANCE = 10000
*/

exec MARKET_PLACE.ITEM_FAVORITE_TOGGLE @USER_ID=1,@ITEM_ID=4