SELECT * FROM MARKET_PLACE.MARKET_USERS
SELECT * FROM MARKET_PLACE.MARKET_ITEMS
SELECT * FROM MARKET_PLACE.MARKET_ORDERS

SELECT * FROM MARKET_PLACE.ITEM_IMAGES
SELECT * FROM MARKET_PLACE.HISTORY
SELECT * FROM MARKET_PLACE.MARKET_PERSONS

/*
UPDATE MARKET_PLACE.MARKET_USERS
	SET BALANCE = 10000
*/