SELECT * FROM MARKET_PLACE.MARKET_USERS
SELECT * FROM MARKET_PLACE.MARKET_ITEMS
SELECT * FROM MARKET_PLACE.MARKET_ORDERS

SELECT * FROM MARKET_PLACE.ITEM_IMAGES
SELECT * FROM MARKET_PLACE.HISTORY
SELECT * FROM MARKET_PLACE.MARKET_PERSONS

SELECT * FROM MARKET_PLACE.ITEMS_FAVORITE

/*
UPDATE MARKET_PLACE.MARKET_USERS
	SET BALANCE = 10000
*/

exec MARKET_PLACE.ITEMS_GET_BY_PAGE_WITH_FILTER @PAGE_NO=1,@PAGE_COUNT=20,@ITEM_CATEGORY=default,@MARKET_USER_ID=1,@FILTER_BY_HIGHEST_BIDDER=default,@FILTER_BY_OWNER_ID=0,@ORDER_BY_PRICE=default,@ORDER_BY_DATE=default,@ONLY_FAV=default