CREATE OR ALTER PROCEDURE MARKET_PLACE.USER_REGISTRATION
(
	@USER_LOGIN VARCHAR(50),
	@USER_PASSWORD NVARCHAR(50)
)
AS BEGIN

	INSERT INTO MARKET_PLACE.MARKET_USERS(USER_LOGIN, USER_PASSWORD, REG_DATE)
	VALUES (@USER_LOGIN, @USER_PASSWORD, GETDATE())

END;
GO

CREATE OR ALTER PROCEDURE MARKET_PLACE.USER_AUTHORIZATION
(
	@USER_LOGIN VARCHAR(50),
	@USER_PASSWORD NVARCHAR(50),

	@USER_ID INT OUTPUT,
	@USER_LEVEL INT OUTPUT
)
AS BEGIN

	SELECT
		@USER_ID = ID,
		@USER_LEVEL = USER_LEVEL
	FROM MARKET_PLACE.MARKET_USERS AS U
	WHERE USER_LOGIN = @USER_LOGIN
		AND USER_PASSWORD = @USER_PASSWORD

END;
GO