CREATE OR ALTER PROCEDURE MARKET_PLACE.USER_REGISTRATION
(
	@USER_LOGIN VARCHAR(50),
	@USER_PASSWORD NVARCHAR(50)
)
AS BEGIN

	INSERT INTO MARKET_PLACE.MARKET_USERS(USER_LOGIN, USER_PASSWORD, REG_DATE)
	VALUES (@USER_LOGIN, @USER_PASSWORD, GETDATE())

END;
GO