CREATE OR ALTER PROCEDURE MARKET_PLACE.ITEMS_GET_BY_PAGE_WITH_FILTER
(
	@PAGE_NO INT = 1,
	@PAGE_COUNT INT = 10,
	@ITEM_CATEGORY TINYINT = NULL,
	@OWNER_ID INT,
	@HIGHEST_BIDDER INT = NULL,
	@FILTER_BY_OWNER_ID BIT = 0, -- 0 - except owner's items, 1 - only owner's items
	@ORDER_BY_PRICE_ASC BIT = 0,
	@ORDER_BY_PRICE_DESC BIT = 0,
	@ORDER_BY_DATE_ASC BIT = 0,
	@ORDER_BY_DATE_DESC BIT = 0
)
AS BEGIN

	SELECT
		ID,
		TITLE,
		ITEM_DESCRIPTION,
		ITEM_CATEGORY,
		START_PRICE,
		END_PRICE,
		CURRENT_PRICE,
		BID_STEP,
		DATE_START,
		DATE_END,
		HIGHEST_BIDDER,
		OWNER_ID
	FROM MARKET_PLACE.MARKET_ITEMS AS  I

END;
GO